// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gclient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InstaMediaClient is the client API for InstaMedia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InstaMediaClient interface {
	// 检查服务端状态
	ServerCheck(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRes, error)
	// 获取媒体地址
	GetMedia(ctx context.Context, in *ShareURL, opts ...grpc.CallOption) (*MediaURLs, error)
}

type instaMediaClient struct {
	cc grpc.ClientConnInterface
}

func NewInstaMediaClient(cc grpc.ClientConnInterface) InstaMediaClient {
	return &instaMediaClient{cc}
}

func (c *instaMediaClient) ServerCheck(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRes, error) {
	out := new(AuthRes)
	err := c.cc.Invoke(ctx, "/pb.InstaMedia/ServerCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instaMediaClient) GetMedia(ctx context.Context, in *ShareURL, opts ...grpc.CallOption) (*MediaURLs, error) {
	out := new(MediaURLs)
	err := c.cc.Invoke(ctx, "/pb.InstaMedia/GetMedia", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstaMediaServer is the server API for InstaMedia service.
// All implementations must embed UnimplementedInstaMediaServer
// for forward compatibility
type InstaMediaServer interface {
	// 检查服务端状态
	ServerCheck(context.Context, *AuthReq) (*AuthRes, error)
	// 获取媒体地址
	GetMedia(context.Context, *ShareURL) (*MediaURLs, error)
	mustEmbedUnimplementedInstaMediaServer()
}

// UnimplementedInstaMediaServer must be embedded to have forward compatible implementations.
type UnimplementedInstaMediaServer struct {
}

func (UnimplementedInstaMediaServer) ServerCheck(context.Context, *AuthReq) (*AuthRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerCheck not implemented")
}
func (UnimplementedInstaMediaServer) GetMedia(context.Context, *ShareURL) (*MediaURLs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedia not implemented")
}
func (UnimplementedInstaMediaServer) mustEmbedUnimplementedInstaMediaServer() {}

// UnsafeInstaMediaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstaMediaServer will
// result in compilation errors.
type UnsafeInstaMediaServer interface {
	mustEmbedUnimplementedInstaMediaServer()
}

func RegisterInstaMediaServer(s grpc.ServiceRegistrar, srv InstaMediaServer) {
	s.RegisterService(&InstaMedia_ServiceDesc, srv)
}

func _InstaMedia_ServerCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstaMediaServer).ServerCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InstaMedia/ServerCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstaMediaServer).ServerCheck(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstaMedia_GetMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareURL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstaMediaServer).GetMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InstaMedia/GetMedia",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstaMediaServer).GetMedia(ctx, req.(*ShareURL))
	}
	return interceptor(ctx, in, info, handler)
}

// InstaMedia_ServiceDesc is the grpc.ServiceDesc for InstaMedia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstaMedia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.InstaMedia",
	HandlerType: (*InstaMediaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerCheck",
			Handler:    _InstaMedia_ServerCheck_Handler,
		},
		{
			MethodName: "GetMedia",
			Handler:    _InstaMedia_GetMedia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "instago.proto",
}
